import type {Job} from '~~/shared/types/job'

export const JOBS: Job[] = [
    {
        id: '1',
        docketNo: 'WO-1042',
        title: 'Frontend Developer',
        company: 'Anvil Systems',
        location: 'Köln, DE',
        employment: 'Full-time',
        salary: '€55k–€70k',
        status: 'open',
        tags: ['Vue', 'TypeScript', 'CSS'],
        summary: 'Build the interface for a warehouse inventory platform used on the floor, not just in the office.',
        description: [
            'Anvil Systems makes the handheld scanning software that warehouse crews use to track pallets in and out. You would own the Vue front end end-to-end: the scan queue, offline sync, and the shift-report screens.',
            'Most of our users wear gloves and work under fluorescent light, so legibility and touch targets matter more than polish. You will spend real time in the warehouse watching people use what you build.',
        ],
        applyUrl: 'mailto:jobs@anvilsystems.example',
        postedAt: '2026-07-02',
    },
    {
        id: '2',
        docketNo: 'WO-1058',
        title: 'Backend Engineer',
        company: 'Northline Logistics',
        location: 'Remote (EU)',
        employment: 'Full-time',
        salary: '€60k–€80k',
        status: 'open',
        tags: ['Go', 'PostgreSQL'],
        summary: 'Keep freight dispatch running on time across three time zones.',
        description: [
            'Northline routes freight for regional carriers across Germany, Poland, and the Netherlands. Our dispatch service assigns loads to trucks in real time, and it cannot afford to be slow or wrong.',
            'You would work in Go on the dispatch and routing service, with a small team that carries a shared on-call rotation. We ship daily and read every incident postmortem out loud.',
        ],
        applyUrl: 'mailto:jobs@northline-logistics.example',
        postedAt: '2026-06-24',
    },
    {
        id: '3',
        docketNo: 'WO-1071',
        title: 'Product Designer',
        company: 'Fernweh Studio',
        location: 'Lisbon, PT',
        employment: 'Contract',
        status: 'open',
        tags: ['Figma', 'Design systems'],
        summary: 'Design the booking flow for a travel app used by people planning their first solo trip.',
        description: [
            'Fernweh helps first-time solo travelers plan trips without the anxiety of doing it alone. You would redesign the itinerary builder and the in-app booking flow, and maintain the component library both live in.',
            'This is a six-month contract with a strong chance of extension. We work in the open with a small, opinionated team and ship weekly.',
        ],
        applyUrl: 'mailto:jobs@fernwehstudio.example',
        postedAt: '2026-06-29',
    },
    {
        id: '4',
        docketNo: 'WO-1089',
        title: 'Data Analyst',
        company: 'Ledger & Co',
        location: 'Remote',
        employment: 'Part-time',
        status: 'filled',
        tags: ['SQL', 'Looker'],
        summary: 'Built the weekly reporting suite for a bookkeeping firm serving 400 small businesses.',
        description: [
            'Ledger & Co provides bookkeeping for small businesses that cannot afford a full finance team. This role built the client-facing dashboards that show cash flow and burn rate.',
            'This docket has been filled, but Ledger & Co posts similar roles a few times a year — worth checking back.',
        ],
        applyUrl: 'mailto:jobs@ledgerandco.example',
        postedAt: '2026-05-18',
    },
    {
        id: '5',
        docketNo: 'WO-1103',
        title: 'Platform Engineer',
        company: 'Circuit Robotics',
        location: 'Eindhoven, NL',
        employment: 'Full-time',
        salary: '€65k–€85k',
        status: 'open',
        tags: ['Kubernetes', 'Terraform'],
        summary: 'Run the infrastructure that a fleet of warehouse robots reports back to.',
        description: [
            'Circuit builds autonomous robots for warehouse picking. Every robot streams telemetry back to a cluster you would help run and provision.',
            'You would own the Kubernetes and Terraform setup for our fleet-management backend, and help decide what gets automated next.',
        ],
        applyUrl: 'mailto:jobs@circuitrobotics.example',
        postedAt: '2026-07-04',
    },
    {
        id: '6',
        docketNo: 'WO-1114',
        title: 'Support Engineer',
        company: 'Pinecrest Health',
        location: 'Remote (US)',
        employment: 'Full-time',
        status: 'filled',
        tags: ['Zendesk', 'SQL'],
        summary: 'Answered the phone when a clinic\'s scheduling software went down mid-shift.',
        description: [
            'Pinecrest makes scheduling software for outpatient clinics. This role was the first line of support when something broke during clinic hours, which meant fast triage and clear writing.',
            'This docket has been filled. Pinecrest hires for this role seasonally, usually posting again toward the end of the year.',
        ],
        applyUrl: 'mailto:jobs@pinecresthealth.example',
        postedAt: '2026-06-10',
    },
    {
        id: '7',
        docketNo: 'WO-1114',
        title: 'Support Engineer',
        company: 'Pinecrest Health',
        location: 'Remote (US)',
        employment: 'Full-time',
        status: 'open',
        tags: ['Zendesk', 'SQL'],
        summary: 'Answered the phone when a clinic\'s scheduling software went down mid-shift.',
        description: [
            'Pinecrest makes scheduling software for outpatient clinics. This role was the first line of support when something broke during clinic hours, which meant fast triage and clear writing.',
            'This docket has been filled. Pinecrest hires for this role seasonally, usually posting again toward the end of the year.',
        ],
        applyUrl: 'mailto:jobs@pinecresthealth.example',
        postedAt: '2026-06-10',
    },
]
