import type {Job} from '~~/shared/types/job'

export const JOBS: Job[] = [
    {
        id: '1',
        docketNo: 'WO-1042',
        title: 'Frontend Developer',
        company: 'Anvil Systems',
        location: 'Köln, DE',
        employment: 'Full-time',
        salary: '€55k–€70k',
        status: 'open',
        tags: ['Vue', 'TypeScript', 'CSS'],
        summary: 'Build the interface for a warehouse inventory platform used on the floor, not just in the office.',
        description: [
            'Anvil Systems makes the handheld scanning software that warehouse crews use to track pallets in and out. You would own the Vue front end end-to-end: the scan queue, offline sync, and the shift-report screens.',
            'Most of our users wear gloves and work under fluorescent light, so legibility and touch targets matter more than polish. You will spend real time in the warehouse watching people use what you build.',
        ],
        applyUrl: 'mailto:jobs@anvilsystems.example',
        postedAt: '2026-07-02',
    },
    {
        id: '2',
        docketNo: 'WO-1058',
        title: 'Backend Engineer',
        company: 'Northline Logistics',
        location: 'Remote (EU)',
        employment: 'Full-time',
        salary: '€60k–€80k',
        status: 'open',
        tags: ['Go', 'PostgreSQL'],
        summary: 'Keep freight dispatch running on time across three time zones.',
        description: [
            'Northline routes freight for regional carriers across Germany, Poland, and the Netherlands. Our dispatch service assigns loads to trucks in real time, and it cannot afford to be slow or wrong.',
            'You would work in Go on the dispatch and routing service, with a small team that carries a shared on-call rotation. We ship daily and read every incident postmortem out loud.',
        ],
        applyUrl: 'mailto:jobs@northline-logistics.example',
        postedAt: '2026-06-24',
    },
    {
        id: '3',
        docketNo: 'WO-1071',
        title: 'Product Designer',
        company: 'Fernweh Studio',
        location: 'Lisbon, PT',
        employment: 'Contract',
        status: 'open',
        tags: ['Figma', 'Design systems'],
        summary: 'Design the booking flow for a travel app used by people planning their first solo trip.',
        description: [
            'Fernweh helps first-time solo travelers plan trips without the anxiety of doing it alone. You would redesign the itinerary builder and the in-app booking flow, and maintain the component library both live in.',
            'This is a six-month contract with a strong chance of extension. We work in the open with a small, opinionated team and ship weekly.',
        ],
        applyUrl: 'mailto:jobs@fernwehstudio.example',
        postedAt: '2026-06-29',
    },
    {
        id: '4',
        docketNo: 'WO-1089',
        title: 'Data Analyst',
        company: 'Ledger & Co',
        location: 'Remote',
        employment: 'Part-time',
        status: 'filled',
        tags: ['SQL', 'Looker'],
        summary: 'Built the weekly reporting suite for a bookkeeping firm serving 400 small businesses.',
        description: [
            'Ledger & Co provides bookkeeping for small businesses that cannot afford a full finance team. This role built the client-facing dashboards that show cash flow and burn rate.',
            'This docket has been filled, but Ledger & Co posts similar roles a few times a year — worth checking back.',
        ],
        applyUrl: 'mailto:jobs@ledgerandco.example',
        postedAt: '2026-05-18',
    },
    {
        id: '5',
        docketNo: 'WO-1103',
        title: 'Platform Engineer',
        company: 'Circuit Robotics',
        location: 'Eindhoven, NL',
        employment: 'Full-time',
        salary: '€65k–€85k',
        status: 'open',
        tags: ['Kubernetes', 'Terraform'],
        summary: 'Run the infrastructure that a fleet of warehouse robots reports back to.',
        description: [
            'Circuit builds autonomous robots for warehouse picking. Every robot streams telemetry back to a cluster you would help run and provision.',
            'You would own the Kubernetes and Terraform setup for our fleet-management backend, and help decide what gets automated next.',
        ],
        applyUrl: 'mailto:jobs@circuitrobotics.example',
        postedAt: '2026-07-04',
    },
    {
        id: '6',
        docketNo: 'WO-1114',
        title: 'Support Engineer',
        company: 'Pinecrest Health',
        location: 'Remote (US)',
        employment: 'Full-time',
        status: 'filled',
        tags: ['Zendesk', 'SQL'],
        summary: 'First line of support when a clinic\'s scheduling software went down mid-shift.',
        description: [
            'Pinecrest makes scheduling software for outpatient clinics. This role was the first line of support when something broke during clinic hours, which meant fast triage and clear writing.',
            'This docket has been filled. Pinecrest hires for this role seasonally, usually posting again toward the end of the year.',
        ],
        applyUrl: 'mailto:jobs@pinecresthealth.example',
        postedAt: '2026-06-10',
    },
    {
        id: '7',
        docketNo: 'WO-1128',
        title: 'Frontend Developer',
        company: 'Kestrel Analytics',
        location: 'Berlin, DE',
        employment: 'Full-time',
        salary: '€58k–€72k',
        status: 'open',
        tags: ['React', 'TypeScript'],
        summary: 'Build dashboards that turn ad-spend data into decisions marketers actually make.',
        description: [
            'Kestrel gives small marketing teams the kind of reporting that usually only agencies can afford. You would build the charting and filtering layer in React on top of a fast query API.',
            'The hard part is not the charts, it is making them legible to people who are not analysts. We test every screen with real customers before it ships.',
        ],
        applyUrl: 'mailto:jobs@kestrelanalytics.example',
        postedAt: '2026-06-27',
    },
    {
        id: '8',
        docketNo: 'WO-1136',
        title: 'Full-stack Developer',
        company: 'Tideway Bank',
        location: 'Frankfurt, DE',
        employment: 'Full-time',
        salary: '€62k–€78k',
        status: 'open',
        tags: ['Vue', 'Node.js', 'PostgreSQL'],
        summary: 'Ship features across the stack for a digital bank that answers to regulators.',
        description: [
            'Tideway is a small digital bank where the same engineer often carries a feature from the Vue front end down to the Node service and the Postgres schema. Nothing ships without an audit trail.',
            'You would work in a squad with a product owner and a compliance reviewer embedded. It is slower than a startup and far more deliberate — on purpose.',
        ],
        applyUrl: 'mailto:jobs@tidewaybank.example',
        postedAt: '2026-06-19',
    },
    {
        id: '9',
        docketNo: 'WO-1144',
        title: 'Data Engineer',
        company: 'Meridian Labs',
        location: 'Remote (EU)',
        employment: 'Full-time',
        salary: '€64k–€82k',
        status: 'open',
        tags: ['Python', 'PostgreSQL', 'AWS'],
        summary: 'Own the pipelines that feed a genomics research platform.',
        description: [
            'Meridian processes sequencing data for research labs, which means large files, strict provenance, and no room for silent data loss. You would own the ingestion and transformation pipelines in Python.',
            'Correctness beats speed here — a wrong number can send a lab down a dead end for months. We reprocess and reconcile obsessively.',
        ],
        applyUrl: 'mailto:jobs@meridianlabs.example',
        postedAt: '2026-07-01',
    },
    {
        id: '10',
        docketNo: 'WO-1151',
        title: 'Mobile Developer',
        company: 'Halcyon Games',
        location: 'München, DE',
        employment: 'Full-time',
        salary: '€60k–€75k',
        status: 'open',
        tags: ['Kotlin', 'Swift'],
        summary: 'Build the client for a cozy multiplayer game with a very patient community.',
        description: [
            'Halcyon makes a slow, cozy multiplayer game that people play for years. You would work on the native mobile clients in Kotlin and Swift, keeping them smooth on old phones.',
            'Our players notice everything and forgive nothing about performance regressions. Battery life is a feature, not an afterthought.',
        ],
        applyUrl: 'mailto:jobs@halcyongames.example',
        postedAt: '2026-06-15',
    },
    {
        id: '11',
        docketNo: 'WO-1159',
        title: 'UX Researcher',
        company: 'Brightfield',
        location: 'Amsterdam, NL',
        employment: 'Contract',
        status: 'open',
        tags: ['Figma', 'Research'],
        summary: 'Run the interviews that decide what a farming-logistics app builds next.',
        description: [
            'Brightfield builds software for produce cooperatives, and the users are farmers and depot managers, not desk workers. You would run field interviews and turn them into decisions the product team can act on.',
            'This is a four-month contract with a lot of travel to depots and farms. Comfort with muddy boots and bad wifi required.',
        ],
        applyUrl: 'mailto:jobs@brightfield.example',
        postedAt: '2026-06-21',
    },
    {
        id: '12',
        docketNo: 'WO-1167',
        title: 'DevOps Engineer',
        company: 'Ostwind Energy',
        location: 'Hamburg, DE',
        employment: 'Full-time',
        salary: '€66k–€84k',
        status: 'open',
        tags: ['Kubernetes', 'Terraform', 'AWS'],
        summary: 'Keep the platform that monitors offshore wind turbines online in any weather.',
        description: [
            'Ostwind runs monitoring for offshore wind farms, where a dropped connection can mean a turbine spinning blind. You would own the Kubernetes clusters and the Terraform that provisions them.',
            'On-call here is real — storms do not wait for business hours — but the rotation is generous and the incidents teach you a lot.',
        ],
        applyUrl: 'mailto:jobs@ostwindenergy.example',
        postedAt: '2026-07-03',
    },
    {
        id: '13',
        docketNo: 'WO-1175',
        title: 'Frontend Developer',
        company: 'Cobbler & Sons',
        location: 'Remote',
        employment: 'Part-time',
        status: 'open',
        tags: ['Vue', 'CSS'],
        summary: 'Rebuild the storefront for a third-generation shoe repair shop going online.',
        description: [
            'Cobbler & Sons has fixed shoes for sixty years and is finally selling care kits online. You would build a small, fast Vue storefront that feels as unfussy as the shop itself.',
            'This is a part-time role, roughly two days a week, ideal alongside other work. The owner is not technical and trusts you to make the calls.',
        ],
        applyUrl: 'mailto:jobs@cobblerandsons.example',
        postedAt: '2026-06-05',
    },
    {
        id: '14',
        docketNo: 'WO-1183',
        title: 'QA Engineer',
        company: 'Vantage Retail',
        location: 'Warsaw, PL',
        employment: 'Full-time',
        salary: '€40k–€52k',
        status: 'open',
        tags: ['Playwright', 'TypeScript'],
        summary: 'Build the end-to-end tests that stand between a checkout bug and a lost sale.',
        description: [
            'Vantage runs the checkout for a chain of mid-size retailers, so a broken flow costs real money by the hour. You would own the Playwright suite and push it earlier into the pipeline.',
            'You will be the person who says "not yet" before a release, and the team who thanks you afterward. We are building the culture to back that up.',
        ],
        applyUrl: 'mailto:jobs@vantageretail.example',
        postedAt: '2026-06-12',
    },
    {
        id: '15',
        docketNo: 'WO-1191',
        title: 'Backend Engineer',
        company: 'Lumen Health',
        location: 'Vienna, AT',
        employment: 'Full-time',
        status: 'filled',
        tags: ['Go', 'gRPC'],
        summary: 'Built the appointment service behind a telehealth platform.',
        description: [
            'Lumen connects patients with doctors for video visits, and the scheduling service has to hold up during morning rushes. This role built and hardened that service in Go.',
            'This docket has been filled. Lumen grows in waves and usually reopens backend roles after each funding round.',
        ],
        applyUrl: 'mailto:jobs@lumenhealth.example',
        postedAt: '2026-05-29',
    },
    {
        id: '16',
        docketNo: 'WO-1199',
        title: 'Product Designer',
        company: 'Saffron Foods',
        location: 'Barcelona, ES',
        employment: 'Full-time',
        salary: '€48k–€60k',
        status: 'open',
        tags: ['Figma', 'Design systems'],
        summary: 'Design the ordering experience for a meal-kit service with a loyal, hungry audience.',
        description: [
            'Saffron ships regional Spanish meal kits and lives or dies on how easy the weekly order is. You would own the ordering flow and the design system that keeps it consistent across web and email.',
            'Food photography does a lot of the work here, so you will partner closely with the studio team. Make people hungry, then make checkout invisible.',
        ],
        applyUrl: 'mailto:jobs@saffronfoods.example',
        postedAt: '2026-06-26',
    },
    {
        id: '17',
        docketNo: 'WO-1207',
        title: 'Site Reliability Engineer',
        company: 'Dockside',
        location: 'Remote (EU)',
        employment: 'Full-time',
        salary: '€70k–€90k',
        status: 'open',
        tags: ['Kubernetes', 'Go', 'Prometheus'],
        summary: 'Own the reliability of a payments API that cannot go down quietly.',
        description: [
            'Dockside processes payments for online marketplaces, where downtime is measured in refunds and angry sellers. You would own SLOs, alerting, and the Go tooling that keeps the platform honest.',
            'We practice blameless postmortems and mean it. Your first month is mostly reading incidents and asking why.',
        ],
        applyUrl: 'mailto:jobs@dockside.example',
        postedAt: '2026-06-30',
    },
    {
        id: '18',
        docketNo: 'WO-1215',
        title: 'Frontend Developer',
        company: 'Nimbus CRM',
        location: 'Dublin, IE',
        employment: 'Full-time',
        salary: '€55k–€68k',
        status: 'open',
        tags: ['React', 'GraphQL'],
        summary: 'Make a dense sales CRM feel fast for people who live in it all day.',
        description: [
            'Nimbus is a CRM for small sales teams, which means power users who resent every extra click. You would work in React against a GraphQL API, obsessing over keyboard flows and load times.',
            'The design is deliberately utilitarian; the win is speed, not sparkle. If you like shaving milliseconds, you will like it here.',
        ],
        applyUrl: 'mailto:jobs@nimbuscrm.example',
        postedAt: '2026-06-22',
    },
    {
        id: '19',
        docketNo: 'WO-1223',
        title: 'Data Analyst',
        company: 'Auerbach Legal',
        location: 'Köln, DE',
        employment: 'Part-time',
        status: 'open',
        tags: ['SQL', 'Excel'],
        summary: 'Turn billable-hours data into reports the partners will actually read.',
        description: [
            'Auerbach is a mid-size law firm that finally wants to understand its own numbers. You would build the recurring reports on utilization and realization in SQL and hand them off cleanly.',
            'This is a part-time role with steady hours, well suited to someone who values predictability. The work is quiet, precise, and appreciated.',
        ],
        applyUrl: 'mailto:jobs@auerbachlegal.example',
        postedAt: '2026-06-08',
    },
    {
        id: '20',
        docketNo: 'WO-1231',
        title: 'Security Engineer',
        company: 'Redpine Security',
        location: 'Remote',
        employment: 'Full-time',
        salary: '€72k–€95k',
        status: 'open',
        tags: ['Python', 'Rust'],
        summary: 'Find the bugs before someone with worse intentions does.',
        description: [
            'Redpine does security tooling for other engineering teams, so the work is half offense, half building guardrails. You would split time between Python tooling and Rust for the parts that must be fast and safe.',
            'A background in appsec helps but curiosity matters more. We keep a well-stocked shelf of things that have gone wrong for others.',
        ],
        applyUrl: 'mailto:jobs@redpinesecurity.example',
        postedAt: '2026-07-05',
    },
    {
        id: '21',
        docketNo: 'WO-1239',
        title: 'Engineering Manager',
        company: 'Fjord Media',
        location: 'Berlin, DE',
        employment: 'Full-time',
        salary: '€85k–€105k',
        status: 'open',
        tags: ['Leadership', 'Vue'],
        summary: 'Lead a small front-end team building tools for independent journalists.',
        description: [
            'Fjord builds the CMS and publishing tools that small newsrooms run on. You would manage a team of four front-end engineers, mostly Vue, and still stay close enough to the code to be useful.',
            'This is a hands-on management role, not a calendar-only one. You will do one-on-ones in the morning and unblock a tricky render in the afternoon.',
        ],
        applyUrl: 'mailto:jobs@fjordmedia.example',
        postedAt: '2026-06-18',
    },
    {
        id: '22',
        docketNo: 'WO-1247',
        title: 'Full-stack Developer',
        company: 'Tram & Rail GmbH',
        location: 'Stuttgart, DE',
        employment: 'Full-time',
        status: 'filled',
        tags: ['TypeScript', 'Node.js', 'PostgreSQL'],
        summary: 'Built the internal tooling that keeps a regional transit operator on schedule.',
        description: [
            'Tram & Rail runs regional public transit and needed better internal tools than the vendor gave them. This role built the scheduling and incident dashboards in TypeScript and Node.',
            'This docket has been filled. The team plans to grow again next year as they take more systems in-house.',
        ],
        applyUrl: 'mailto:jobs@tramrail.example',
        postedAt: '2026-05-22',
    },
    {
        id: '23',
        docketNo: 'WO-1255',
        title: 'Frontend Developer',
        company: 'Willow Education',
        location: 'Remote (EU)',
        employment: 'Contract',
        status: 'open',
        tags: ['Vue', 'TypeScript'],
        summary: 'Build accessible learning tools for classrooms with mixed abilities.',
        description: [
            'Willow makes reading tools for primary schools, used by kids with a wide range of abilities. You would build the Vue interface with accessibility as a hard requirement, not a checkbox.',
            'This is a five-month contract tied to the school-year calendar. Real screen-reader testing is part of the job, every sprint.',
        ],
        applyUrl: 'mailto:jobs@willoweducation.example',
        postedAt: '2026-06-14',
    },
    {
        id: '24',
        docketNo: 'WO-1263',
        title: 'Platform Engineer',
        company: 'Basalt Cloud',
        location: 'Remote',
        employment: 'Full-time',
        salary: '€68k–€88k',
        status: 'open',
        tags: ['Terraform', 'AWS', 'Go'],
        summary: 'Build the internal platform other engineers deploy on without thinking about it.',
        description: [
            'Basalt runs a developer platform used by a few hundred internal engineers, and the goal is to make deploys boring. You would work on the Terraform modules and the Go control plane behind self-service.',
            'Success here is invisible — nobody thanks the platform team when it just works. If that trade feels fair to you, we get along.',
        ],
        applyUrl: 'mailto:jobs@basaltcloud.example',
        postedAt: '2026-06-28',
    },
    {
        id: '25',
        docketNo: 'WO-1271',
        title: 'Backend Engineer',
        company: 'Marlow Freight',
        location: 'Rotterdam, NL',
        employment: 'Full-time',
        salary: '€58k–€74k',
        status: 'open',
        tags: ['Java', 'PostgreSQL'],
        summary: 'Work on the customs service that clears cargo through one of Europe\'s busiest ports.',
        description: [
            'Marlow handles customs documentation for cargo moving through Rotterdam, where a stuck container costs money every hour. You would work in Java on the service that files and tracks declarations.',
            'The domain is dense with regulation and edge cases, so patience pays off. The engineers who thrive here enjoy untangling rules.',
        ],
        applyUrl: 'mailto:jobs@marlowfreight.example',
        postedAt: '2026-06-16',
    },
    {
        id: '26',
        docketNo: 'WO-1279',
        title: 'Product Designer',
        company: 'Petal & Stem',
        location: 'Remote',
        employment: 'Part-time',
        status: 'filled',
        tags: ['Figma'],
        summary: 'Designed the subscription flow for a same-day flower delivery service.',
        description: [
            'Petal & Stem delivers flowers same-day in a handful of cities, and the subscription flow is the heart of the business. This role redesigned it and lifted completion noticeably.',
            'This docket has been filled. They tend to bring designers back on a project basis around the spring season.',
        ],
        applyUrl: 'mailto:jobs@petalandstem.example',
        postedAt: '2026-05-14',
    },
    {
        id: '27',
        docketNo: 'WO-1287',
        title: 'Data Engineer',
        company: 'Grid Dynamics',
        location: 'Frankfurt, DE',
        employment: 'Full-time',
        salary: '€63k–€80k',
        status: 'open',
        tags: ['Python', 'Spark', 'AWS'],
        summary: 'Build the pipelines that turn smart-meter readings into grid forecasts.',
        description: [
            'Grid Dynamics forecasts electricity demand from millions of smart-meter readings a day. You would build and tune the Spark pipelines that feed the forecasting models.',
            'The volume is real and the latency targets are tight during peak hours. You will care a lot about where time actually goes in a job.',
        ],
        applyUrl: 'mailto:jobs@griddynamics.example',
        postedAt: '2026-06-23',
    },
    {
        id: '28',
        docketNo: 'WO-1295',
        title: 'Support Engineer',
        company: 'Copper Kettle',
        location: 'Remote (EU)',
        employment: 'Part-time',
        status: 'open',
        tags: ['Zendesk', 'SQL'],
        summary: 'Help small cafés untangle their point-of-sale on the days it misbehaves.',
        description: [
            'Copper Kettle sells point-of-sale software to independent cafés, and support is often the whole relationship. You would handle tickets, dig into the database when needed, and write up fixes clearly.',
            'This is a part-time role with flexible hours across European mornings. Patience and plain writing matter more than deep code here.',
        ],
        applyUrl: 'mailto:jobs@copperkettle.example',
        postedAt: '2026-06-07',
    },
    {
        id: '29',
        docketNo: 'WO-1303',
        title: 'Mobile Developer',
        company: 'Aster Health',
        location: 'Remote',
        employment: 'Full-time',
        salary: '€60k–€78k',
        status: 'open',
        tags: ['React Native', 'TypeScript'],
        summary: 'Build the app that reminds people to take medication without nagging them.',
        description: [
            'Aster makes a medication-reminder app where the hard part is tone: helpful, never guilt-tripping. You would build it in React Native, sweating notification timing and accessibility.',
            'Our users skew older and value calm over clever. Every animation earns its place or it goes.',
        ],
        applyUrl: 'mailto:jobs@asterhealth.example',
        postedAt: '2026-06-25',
    },
    {
        id: '30',
        docketNo: 'WO-1311',
        title: 'Frontend Developer',
        company: 'Vessel Studio',
        location: 'Lisbon, PT',
        employment: 'Full-time',
        salary: '€50k–€64k',
        status: 'open',
        tags: ['Vue', 'CSS', 'TypeScript'],
        summary: 'Build marketing sites for clients who care a lot about the last 5%.',
        description: [
            'Vessel is a small studio that builds fast, beautiful marketing sites for design-forward clients. You would work in Vue with a heavy emphasis on motion, typography, and Core Web Vitals.',
            'The work is varied and the standards are high — the last 5% is the whole job here. You will ship often and take pride in the details nobody names.',
        ],
        applyUrl: 'mailto:jobs@vesselstudio.example',
        postedAt: '2026-07-01',
    },
    {
        id: '31',
        docketNo: 'WO-1319',
        title: 'QA Engineer',
        company: 'Hollow Oak',
        location: 'Remote',
        employment: 'Contract',
        status: 'open',
        tags: ['Playwright', 'Cypress'],
        summary: 'Stand up an end-to-end test suite for a team that has never had one.',
        description: [
            'Hollow Oak makes tabletop-gaming companion apps and has grown faster than its test coverage. You would come in for a contract to build the E2E suite from scratch in Playwright.',
            'This is a three-month contract with a clear deliverable: a green pipeline the team trusts. You leave them able to maintain it without you.',
        ],
        applyUrl: 'mailto:jobs@hollowoak.example',
        postedAt: '2026-06-20',
    },
    {
        id: '32',
        docketNo: 'WO-1327',
        title: 'DevOps Engineer',
        company: 'Steinweg AG',
        location: 'München, DE',
        employment: 'Full-time',
        status: 'filled',
        tags: ['Kubernetes', 'Terraform'],
        summary: 'Migrated a manufacturing company\'s legacy deploys onto Kubernetes.',
        description: [
            'Steinweg makes industrial sensors and had years of hand-rolled deploys to modernize. This role led the migration to Kubernetes and codified everything in Terraform.',
            'This docket has been filled. Steinweg is early in a multi-year modernization and expects to hire again in this space.',
        ],
        applyUrl: 'mailto:jobs@steinweg.example',
        postedAt: '2026-05-26',
    },
    {
        id: '33',
        docketNo: 'WO-1335',
        title: 'UX Researcher',
        company: 'Larkspur',
        location: 'Remote (EU)',
        employment: 'Contract',
        status: 'open',
        tags: ['Research', 'Figma'],
        summary: 'Figure out why users abandon onboarding in a budgeting app.',
        description: [
            'Larkspur makes a personal budgeting app with a leaky onboarding funnel nobody fully understands. You would run the studies to find out where and why people drop, and hand the team something actionable.',
            'This is a short, focused contract — roughly ten weeks — with one clear question to answer. Bring rigor and a bias for saying what the data does not support.',
        ],
        applyUrl: 'mailto:jobs@larkspur.example',
        postedAt: '2026-06-11',
    },
    {
        id: '34',
        docketNo: 'WO-1343',
        title: 'Backend Engineer',
        company: 'Quantum Ledger',
        location: 'Berlin, DE',
        employment: 'Full-time',
        salary: '€66k–€85k',
        status: 'open',
        tags: ['Rust', 'PostgreSQL'],
        summary: 'Build the ledger service where every cent has to reconcile, always.',
        description: [
            'Quantum Ledger provides double-entry accounting infrastructure for fintech startups, so correctness is the entire product. You would work in Rust on the core ledger, where an off-by-one is a incident.',
            'The bar for testing is high and the review culture is exacting. If you find comfort in code that provably balances, this is your place.',
        ],
        applyUrl: 'mailto:jobs@quantumledger.example',
        postedAt: '2026-06-30',
    },
    {
        id: '35',
        docketNo: 'WO-1351',
        title: 'Data Analyst',
        company: 'Bramble & Fig',
        location: 'Amsterdam, NL',
        employment: 'Full-time',
        salary: '€52k–€66k',
        status: 'open',
        tags: ['SQL', 'Looker', 'Python'],
        summary: 'Answer the "why did sales dip" questions for a specialty grocery chain.',
        description: [
            'Bramble & Fig runs a chain of specialty grocery stores and wants analysis, not just dashboards. You would own the reporting in SQL and Looker and reach for Python when the question gets messy.',
            'The best part is proximity to decisions — buyers and store managers actually read your work. The worst part is that they will ask hard follow-ups.',
        ],
        applyUrl: 'mailto:jobs@brambleandfig.example',
        postedAt: '2026-06-17',
    },
]